### ISSUE TITLE
Move away from travisCI

### ISSUE THREAD

**Issue by SimonBaeumer** [commander-cli/commander#160]
travis service is not as good as it was for open source projects.
Alternatives which come to my mind currently:

 - circle CI
 - github actions

@dylanhitt What do you think? Any ideas on this?

**Comment by fbartels** [comment]
Did you mean to write "travis"?

**Comment by SimonBaeumer** [comment]
> Did you mean to write "travis"?

Thank you! Yes I meant travis, corrected it.

**Comment by dylanhitt** [comment]
Mind changing the title as well? 😄 

Yeah, I say we give github actions a shot. I already made #143. Maybe we want to try both?

**Comment by SimonBaeumer** [comment]
Opsi, sorry about that, changed the title 👍   
Then let us give github actions a try first. I would only try both if we are not satisfied with github actions.

**Comment by dylanhitt** [comment]
Just to clarify, #143 is about creating a github action for a `commander` release. Essentially tailoring an action made to just run `commander test/add` (and maybe a few other things since at the end of the day it will just be a container image). As you stated this issue is about moving `commander-cli/commander`'s `CI` to github actions 😄. Sorry for the spam didn't want to mislead with my comment above.
